[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "cython",
]
build-backend = "setuptools.build_meta"

[project]
name = "pfvs"
version = "0.0.1"
description = "A software package for constructing/verifying PFVs"
authors = [{ name = "Nate MacFadden for the Liam McAllister Group" }]
readme = "README.md"
license = {text = "GPL-3.0-or-later"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
]
dependencies = [
    "python-flint",
    "joblib",
    "numba",
    "numpy",
    "ortools",
    "scipy",
]
requires-python = ">=3.9"

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-benchmark",
  "matplotlib",
]

[project.urls]
Repository = "https://github.com/natemacfadden/pfvs"

[tool.setuptools]
packages = ["pfvs", "pfvs.c_kernels"]

[tool.setuptools.package-data]
"pfvs.c_kernels" = ["*.so", "*.pyd"]
